In [1]:
import numpy as np

In [2]:
preprocessed_data = np.load('../data_110620.npz',allow_pickle=True)
times = preprocessed_data["times"]
fluxes = preprocessed_data["fluxes"]
flux_errs = preprocessed_data["flux_errs"]
filters = preprocessed_data["filters"]
classes = preprocessed_data["ids"]

In [3]:
fluxes

array([array([48.717018, 53.273788, 25.680866, 33.278061, 15.789575, 27.769186]),
       array([49.219753, 21.227526, 25.851067, 16.224874, 13.073893]),
       array([66.843063, 12.361461, 53.62289 , 51.213921, 30.630966, 22.121798]),
       ...,
       array([134.048508, 110.502991,  74.174957,  58.029629,  77.219833,
        31.504538,  59.600647,  33.991787,  54.077057,  13.827139]),
       array([36.747936, 40.822311, 35.378639, 22.822931, 31.775585]),
       array([-385.041199, -463.856384, -375.543488, -381.961334, -384.66037 ,
       -363.629028, -318.050629, -227.244568, -267.34613 , -351.846039,
       -403.185089, -387.154083, -377.980621, -346.319458, -205.899857,
        -98.217422, -193.514557, -122.985046, -184.747726, -153.27861 ,
       -210.643799, -177.957367, -184.480331, -179.546204, -182.303284,
       -291.670929, -275.538391, -291.183868, -241.851624, -268.196838,
       -278.868347, -293.764069, -229.193619, -299.923767, -297.457581,
       -256.395081, -297.904

In [4]:
toKeep = []
for i, e_fluxes in enumerate(fluxes):
    
    new_fluxes = [np.log10(f) if f >= 0 else 0 for f in e_fluxes]
    
    fluxes[i] = np.array(new_fluxes)
    if any(new_fluxes):
        toKeep.append(i)

len(fluxes)

756091

In [5]:
len(toKeep)

742121

In [6]:
SNI = (52, 62, 67, 90)

In [7]:
classes_collapsed = classes.copy()

for i, c in enumerate(classes):
    if c in SNI:
        classes_collapsed[i] = 0

In [8]:
times = times[toKeep]
fluxes = fluxes[toKeep]
flux_errs = flux_errs[toKeep]
filters = filters[toKeep]
classes = classes_collapsed[toKeep]

print(len(fluxes))
fluxes

742121


array([array([1.6876807 , 1.72651358, 1.40960966, 1.52215801, 1.19837044,
       1.44356315]),
       array([1.69213943, 1.32689938, 1.41247847, 1.21018133, 1.11640493]),
       array([1.82505634, 1.0920698 , 1.72935022, 1.70938803, 1.48616069,
       1.34482042]),
       ...,
       array([1.29258636, 1.27865004, 1.15756525, 1.45088124, 1.27087773,
       1.05883609]),
       array([2.12726198, 2.04337403, 1.8702573 , 1.76364979, 1.88772886,
       1.49837312, 1.77525097, 1.531374  , 1.73301305, 1.14073233]),
       array([1.56523295, 1.61089759, 1.54874112, 1.35837142, 1.50209355])],
      dtype=object)

In [9]:
np.savez("fulldata.npz", times=times, fluxes=fluxes, flux_errs=flux_errs, filters=filters, ids=classes)